INSERT INTO CAPTCHA(questions, goodAnswer) VALUES('Quel est la capital de Espagne ?', 'madrid');
INSERT INTO CAPTCHA(questions, goodAnswer) VALUES('5 + 3?', '8');
INSERT INTO CAPTCHA(questions, goodAnswer) VALUES('Quel est le jour qui suit le lundi?', 'mardi');
INSERT INTO CAPTCHA(questions, goodAnswer) VALUES('Quelle est la couleur du ciel ?', 'bleu');
INSERT INTO CAPTCHA(questions, goodAnswer) VALUES('Quelle est la capitale de la France ?', 'paris');
INSERT INTO CAPTCHA(questions, goodAnswer) VALUES('Quel est le mois suivant avril ?', 'mai');
INSERT INTO CAPTCHA(questions, goodAnswer) VALUES('Quelle est la couleur du soleil ?', 'jaune');
INSERT INTO CAPTCHA(questions, goodAnswer) VALUES('7 x 7', '49');
INSERT INTO CAPTCHA(questions, goodAnswer) VALUES('Quel est le contraire de "bas" ?', 'haut');
INSERT INTO CAPTCHA(questions, goodAnswer) VALUES('Quel animal dit "meow" ?', 'chat');
INSERT INTO CAPTCHA(questions, goodAnswer) VALUES('Quelle est la couleur du sang ?', 'rouge');
INSERT INTO CAPTCHA(questions, goodAnswer) VALUES('10 - 5', '5');
INSERT INTO CAPTCHA(questions, goodAnswer) VALUES('Quel est le contraire de "jour" ?', 'nuit');
INSERT INTO CAPTCHA(questions, goodAnswer) VALUES('3 x 3', '9');
INSERT INTO CAPTCHA(questions, goodAnswer) VALUES(' Quelle est la capitale du Canada ?', 'ottowa');
INSERT INTO CAPTCHA(questions, goodAnswer) VALUES('Quel animal vole et hulule la nuit ?', 'hibou');
INSERT INTO CAPTCHA(questions, goodAnswer) VALUES('Quelle est la première lettre du mot "orange" ? ', 'o');
INSERT INTO CAPTCHA(questions, goodAnswer) VALUES('Quel est le contraire de "chaud" ?', 'froid');
INSERT INTO CAPTCHA(questions, goodAnswer) VALUES('Quelle est la couleur du feu ?', 'rouge');
INSERT INTO CAPTCHA(questions, goodAnswer) VALUES('Quelle est la capitale du Japon ?', 'tokyo');