INSERT INTO AUTHOR (id_author, name, lastname) VALUES (1, 'Victor' , 'Hugo');
INSERT INTO AUTHOR (id_author, name, lastname) VALUES (2, 'Jane' , 'Austen');
INSERT INTO AUTHOR (id_author, name, lastname) VALUES (3, 'Fiodor' , 'Dostoïevski');
INSERT INTO AUTHOR (id_author, name, lastname) VALUES (4, 'Léon' , 'Tolstoï');
INSERT INTO AUTHOR (id_author, name, lastname) VALUES (5, 'Alexandre' , 'Dumas');
INSERT INTO AUTHOR (id_author, name, lastname) VALUES (6, 'JK' , 'Rowling');
INSERT INTO AUTHOR (id_author, name, lastname) VALUES (7, 'J.R.R.' , 'Tolkien');
INSERT INTO AUTHOR (id_author, name, lastname) VALUES (8, 'Antoine' , 'de Saint-Exupéry');
INSERT INTO AUTHOR (id_author, name, lastname) VALUES (9, 'Ken' , 'Follett');
INSERT INTO AUTHOR (id_author, name, lastname) VALUES (10, 'Margaret' , 'Mitchell');
INSERT INTO AUTHOR (id_author, name, lastname) VALUES (11, 'Charles' , 'Baudelaire');
INSERT INTO AUTHOR (id_author, name, lastname) VALUES (12, 'Walt' , 'Whitman');
INSERT INTO AUTHOR (id_author, name, lastname) VALUES (13, 'Isidore' , 'Ducasse');
INSERT INTO AUTHOR (id_author, name, lastname) VALUES (14, 'Arthur' , 'Rimbaud');
INSERT INTO AUTHOR (id_author, name, lastname) VALUES (15, 'T.S.' , 'Eliot');
INSERT INTO AUTHOR (id_author, name, lastname) VALUES (16, ' William' , 'Shakespeare');
INSERT INTO AUTHOR (id_author, name, lastname) VALUES (17, '' , 'Molière');
INSERT INTO AUTHOR (id_author, name, lastname) VALUES (18, 'Eugène' , 'Ionesco');
INSERT INTO AUTHOR (id_author, name, lastname) VALUES (19, 'Edmond' , 'Rostand');
INSERT INTO AUTHOR (id_author, name, lastname) VALUES (20, 'Pierre' , 'Corneille');
INSERT INTO AUTHOR (id_author, name, lastname) VALUES (21, 'Albert' , 'Camus');
INSERT INTO AUTHOR (id_author, name, lastname) VALUES (22, 'Jean' , 'Giraudoux');
INSERT INTO AUTHOR (id_author, name, lastname) VALUES (23, 'Guy' , 'de Maupassant');
INSERT INTO AUTHOR (id_author, name, lastname) VALUES (24, 'Franz' , 'Kafka');
INSERT INTO AUTHOR (id_author, name, lastname) VALUES (25, 'Oscar' , 'Wild');
INSERT INTO AUTHOR (id_author, name, lastname) VALUES (26, 'Charles' , 'Perrault');
INSERT INTO AUTHOR (id_author, name, lastname) VALUES (27, 'Barbey' , 'd''Aurevilly');
INSERT INTO AUTHOR (id_author, name, lastname) VALUES (28, 'Isaac' , 'Asimov');
INSERT INTO AUTHOR (id_author, name, lastname) VALUES (29, 'George' , 'Orwell');
INSERT INTO AUTHOR (id_author, name, lastname) VALUES (30, 'Frank' , 'Herbert');
INSERT INTO AUTHOR (id_author, name, lastname) VALUES (31, 'William' , 'Gibson');
INSERT INTO AUTHOR (id_author, name, lastname) VALUES (32, 'Edgar' , 'Rice');
INSERT INTO AUTHOR (id_author, name, lastname) VALUES (33, 'Joe' , 'Haldeman');
INSERT INTO AUTHOR (id_author, name, lastname) VALUES (34, 'Philip' , 'K. Dick');
INSERT INTO AUTHOR (id_author, name, lastname) VALUES (35, 'Douglas' , 'Adams');
INSERT INTO AUTHOR (id_author, name, lastname) VALUES (36, 'Arthur' , 'C. Clarke');
INSERT INTO AUTHOR (id_author, name, lastname) VALUES (37, 'Robin' , 'Hobb');
INSERT INTO AUTHOR (id_author, name, lastname) VALUES (38, 'C.S.' , 'Lewis');
INSERT INTO AUTHOR (id_author, name, lastname) VALUES (39, 'David' , 'Eddings');
INSERT INTO AUTHOR (id_author, name, lastname) VALUES (40, 'Robert' , 'Jordan');
INSERT INTO AUTHOR (id_author, name, lastname) VALUES (41, 'Patrick' , 'Rothfuss');
INSERT INTO AUTHOR (id_author, name, lastname) VALUES (42, 'Brandon' , 'Sanderson');
INSERT INTO AUTHOR (id_author, name, lastname) VALUES (43, 'Pierre' , 'Bottero');
INSERT INTO AUTHOR (id_author, name, lastname) VALUES (44, 'Tui' , 'T. Sutherland');
INSERT INTO AUTHOR (id_author, name, lastname) VALUES (45, 'Arthur' , 'Conan Doyle');

INSERT INTO AUTHOR (id_author, name, lastname) VALUES (46, 'Gaston' , 'Leroux');
INSERT INTO AUTHOR (id_author, name, lastname) VALUES (47, 'Stieg' , 'Larsson');
INSERT INTO AUTHOR (id_author, name, lastname) VALUES (48, 'Paula' , 'Hawkins');
INSERT INTO AUTHOR (id_author, name, lastname) VALUES (49, 'Charlotte' , 'Ellison');

