INSERT INTO DISCUSSION_CATEGORIE VALUES ('rules', 'Règles et modération', 'Accueil');
INSERT INTO DISCUSSION_CATEGORIE VALUES ('pres', 'Présentation des membres', 'Accueil');
INSERT INTO DISCUSSION_CATEGORIE VALUES ('authr', 'Auteurs', 'Lecture');
INSERT INTO DISCUSSION_CATEGORIE VALUES ('roman', 'Romans classiques', 'Lecture');
INSERT INTO DISCUSSION_CATEGORIE VALUES ('thril', 'Thriller et Policiers', 'Lecture');
INSERT INTO DISCUSSION_CATEGORIE VALUES ('scifi', 'Science-Fiction et Fantasy', 'Lecture');
INSERT INTO DISCUSSION_CATEGORIE VALUES ('love', 'Romances', 'Lecture');
INSERT INTO DISCUSSION_CATEGORIE VALUES ('manga', 'BD et mangas', 'Lecture');
INSERT INTO DISCUSSION_CATEGORIE VALUES ('event', 'Evènements', 'Communauté');
INSERT INTO DISCUSSION_CATEGORIE VALUES ('chall', 'Challenges', 'Communauté');
